[package]
name = "attempt_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.7"
nannou = "0.18.1"

[profile.dev.package."*"]
opt-level = 3
